version: '4'
services:
  mongodb:
    image: mysql:8.3.0
    container_name: api-committee-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql:/var/lib/mysql