server:
  port: 9090

spring:
  application:
    name: api-committee
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:problemdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true

